name: build-main-amd64

on:
  workflow_dispatch:


env:
  MAIN_TEST_TAG: vojkovic/searxng:production-test
  MAIN_PROD_TAG: vojkovic/searxng:production
  MAIN_GITHUB_PROD_TAG: ghcr.io/privau/searxng:production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vojkovic
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Main Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./
          file: ./Dockerfile
          tags: ${{ env.MAIN_TEST_TAG }}

      - name: Test Main Image
        run: |
          docker run -d -p 8080:8080 ${{ env.MAIN_TEST_TAG }}
          sleep 5 # Give the container some time to start
          curl http://localhost:8080/healthz > input.txt
          cat input.txt
          grep "OK" input.txt
          curl http://localhost:8080/search?q=github > input.txt
          cat input.txt
          grep "data-copied-text" input.txt
          docker rm -f $(docker ps -q --filter ancestor=${{ env.MAIN_TEST_TAG }}) # Stop the container

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.MAIN_PROD_TAG }}
            ${{ env.MAIN_GITHUB_PROD_TAG }}
